// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the reader settled for one champion.
 *
 * **An entry existing is the decision.** A champion with no entry is one the
 * reader never spoke about, and champion select leaves it alone; a champion
 * with an entry is one they settled, and champion select acts on it every
 * game. Nothing that is not a decision belongs in here - see
 * [`Profile::champion_favorites`] for the other half.
 */
export type ChampionPreference = { 
/**
 * The mod applied when this champion is picked, if any.
 *
 * `None` means the champion has no mod of its own, which is different from
 * having one that is currently disabled.
 */
preferred?: string | null, };
