// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What one champion's mods should do, as the reader set them.
 */
export type ChampionPreference = { 
/**
 * The mod applied when this champion is picked, if any.
 *
 * `None` means the champion has no mod of its own, which is different from
 * having one that is currently disabled.
 */
preferred?: string | null, 
/**
 * Mods the reader keeps within reach for this champion, in their order.
 *
 * Champion select offers these first. A mod being here says nothing about
 * whether it is enabled.
 */
favorites: Array<string>, };
