// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DesiredMod } from "./DesiredMod";

/**
 * The scheduler's view of the world, for a frontend that has just mounted.
 */
export type ChampSelectStatus = { 
/**
 * The champion and mod the overlay should be carrying, when there is one.
 */
wanted?: DesiredMod | null, 
/**
 * What it was last made to carry.
 */
applied?: DesiredMod | null, 
/**
 * What a rebuild is currently expected to cost on this machine.
 */
rebuildMs: number, 
/**
 * How long there is after champion select ends, on this machine.
 */
tailMs: number, };
