// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What crosses to the frontend: the local player's part of the session.
 */
export type ChampSelectView = { gameId: number, 
/**
 * The champion the local player has locked, once they have.
 */
lockedChampionId: number | null, 
/**
 * The champion the local player is hovering, while they have not locked.
 */
hoveredChampionId: number | null, 
/**
 * The timer phase, as the client spells it.
 */
timerPhase: string, timeLeftMs: number, 
/**
 * Whether the champion can still change after a lock: an offered trade is
 * open, or the ARAM bench is.
 *
 * A trade *slot* does not count. The client lists one per teammate in
 * every mode, so counting those reports every Practice Tool select as
 * still changeable, which a live capture on 2026-09-15 is what caught.
 */
canStillChange: boolean, 
/**
 * Champions on the ARAM bench, for a reroll or a swap.
 */
benchChampionIds: Array<number>, };
