// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One champion as the client lists it.
 */
export type ChampionSummary = { id: number, name: string, 
/**
 * The internal name, which is the stem of the champion's WAD.
 */
alias: string, };
