// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChampionSummary } from "./ChampionSummary";

/**
 * A champion and the mods installed for it.
 */
export type ChampionMods = { champion: ChampionSummary, modIds: Array<string>, };
