// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The gameflow phase, spelled the way the client spelled it.
 */
export type GameflowChanged = { phase: string, };
