// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether a League client is answering, and on which port.
 */
export type LcuClientState = { connected: boolean, port: number | null, };
