// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChampSelectView } from "./ChampSelectView";

/**
 * What the watch last saw, for a caller that arrives after the events did.
 */
export type LcuSnapshot = { connected: boolean, port: number | null, 
/**
 * The gameflow phase as the client spells it, once one was read.
 */
phase: string | null, 
/**
 * The champion select being followed, while there is one.
 */
champSelect: ChampSelectView | null, };
