// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChampionPreference } from "./ChampionPreference";
import type { ProfileSlug } from "./ProfileSlug";

/**
 * A mod profile for organizing different mod configurations.
 */
export type Profile = { 
/**
 * Unique identifier (UUID)
 */
id: string, 
/**
 * User-friendly name
 */
name: string, 
/**
 * Slugified name used as the filesystem directory name
 */
slug: ProfileSlug, 
/**
 * List of mod IDs enabled in this profile (maintains overlay priority order)
 */
enabledMods: Array<string>, 
/**
 * Display order of all mods (enabled and disabled) in the UI
 */
modOrder: Array<string>, 
/**
 * Per-mod layer enabled/disabled states: mod_id → (layer_name → enabled).
 */
layerStates: { [key in string]: { [key in string]: boolean } }, 
/**
 * What the reader wants applied to each champion, keyed by the champion's
 * alias - `MonkeyKing`, never `Wukong` - because the alias is the one
 * spelling the client does not localize.
 *
 * A record rather than a cache: nothing recomputes it, and losing it loses
 * something the reader chose. It lives on the profile because a preference
 * is about a set of enabled mods, and that set is what a profile is. See
 * ADR-0041.
 */
championPreferences: { [key in string]: ChampionPreference }, 
/**
 * Creation timestamp
 */
createdAt: string, 
/**
 * Last time this profile was used/switched to
 */
lastUsed: string, };
