// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChampionPreference } from "./ChampionPreference";
import type { ProfileSlug } from "./ProfileSlug";

/**
 * A mod profile for organizing different mod configurations.
 */
export type Profile = { 
/**
 * Unique identifier (UUID)
 */
id: string, 
/**
 * User-friendly name
 */
name: string, 
/**
 * Slugified name used as the filesystem directory name
 */
slug: ProfileSlug, 
/**
 * List of mod IDs enabled in this profile (maintains overlay priority order)
 */
enabledMods: Array<string>, 
/**
 * Display order of all mods (enabled and disabled) in the UI
 */
modOrder: Array<string>, 
/**
 * Per-mod layer enabled/disabled states: mod_id → (layer_name → enabled).
 */
layerStates: { [key in string]: { [key in string]: boolean } }, 
/**
 * What the reader wants applied to each champion, keyed by the champion's
 * alias - `MonkeyKing`, never `Wukong` - because the alias is the one
 * spelling the client does not localize.
 *
 * A record rather than a cache: nothing recomputes it, and losing it loses
 * something the reader chose. It lives on the profile because a preference
 * is about a set of enabled mods, and that set is what a profile is. See
 * ADR-0041.
 */
championPreferences: { [key in string]: ChampionPreference }, 
/**
 * The mods the reader keeps within reach for each champion, in the order
 * champion select offers them, keyed by the champion's alias.
 *
 * Beside [`champion_preferences`](Self::champion_preferences) rather than
 * inside it, because the two answer different questions and only one of
 * them is a decision. An entry in the preferences means the reader settled
 * what the champion applies, and champion select acts on that; a favourite
 * says only where a mod sits in a list. Held together, marking a favourite
 * would write a preference, and a preference with no mod in it is the
 * reader having chosen *no* mod - so ordering a list would switch mods
 * off. Apart, neither can be mistaken for the other.
 */
championFavorites: { [key in string]: Array<string> }, 
/**
 * Creation timestamp
 */
createdAt: string, 
/**
 * Last time this profile was used/switched to
 */
lastUsed: string, };
