// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why a swap was not attempted, in the reader's terms rather than the code's.
 *
 * Crosses IPC as a code with its fields, never as a sentence: the frontend
 * owns every string a reader sees (ADR-0017).
 */
export type Refusal = { "code": "patcherIdle" } | { "code": "patcherBuilding" } | { "code": "gameAlreadyRunning" } | { "code": "gameStarting" } | { "code": "champSelectOver" } | { "code": "buildInFlight" } | { "code": "notEnoughTime", needed_ms: number, available_ms: number, };
