// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Refusal } from "./Refusal";

/**
 * What the scheduler concluded, for the interface to draw.
 *
 * A code and typed fields rather than a sentence, per ADR-0017.
 */
export type SwapReport = { "status": "applied", champion: string, modId?: string | null, tookMs: number, } | { "status": "refused", champion: string, modId?: string | null, why: Refusal, } | { "status": "failed", champion: string, modId?: string | null, detail: string, };
