/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkshopRouteImport } from './routes/workshop'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ModsRouteImport } from './routes/mods'
import { Route as DiagnosticsRouteImport } from './routes/diagnostics'
import { Route as ChampionsRouteImport } from './routes/champions'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkshopIndexRouteImport } from './routes/workshop/index'
import { Route as WorkshopProjectNameRouteImport } from './routes/workshop/$projectName'
import { Route as ModsFolderFolderIdRouteImport } from './routes/mods_.folder.$folderId'

const WorkshopRoute = WorkshopRouteImport.update({
  id: '/workshop',
  path: '/workshop',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ModsRoute = ModsRouteImport.update({
  id: '/mods',
  path: '/mods',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticsRoute = DiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => rootRouteImport,
} as any)
const ChampionsRoute = ChampionsRouteImport.update({
  id: '/champions',
  path: '/champions',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkshopIndexRoute = WorkshopIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkshopRoute,
} as any)
const WorkshopProjectNameRoute = WorkshopProjectNameRouteImport.update({
  id: '/$projectName',
  path: '/$projectName',
  getParentRoute: () => WorkshopRoute,
} as any)
const ModsFolderFolderIdRoute = ModsFolderFolderIdRouteImport.update({
  id: '/mods_/folder/$folderId',
  path: '/mods/folder/$folderId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/champions': typeof ChampionsRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/mods': typeof ModsRoute
  '/settings': typeof SettingsRoute
  '/workshop': typeof WorkshopRouteWithChildren
  '/workshop/$projectName': typeof WorkshopProjectNameRoute
  '/workshop/': typeof WorkshopIndexRoute
  '/mods/folder/$folderId': typeof ModsFolderFolderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/champions': typeof ChampionsRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/mods': typeof ModsRoute
  '/settings': typeof SettingsRoute
  '/workshop/$projectName': typeof WorkshopProjectNameRoute
  '/workshop': typeof WorkshopIndexRoute
  '/mods/folder/$folderId': typeof ModsFolderFolderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/champions': typeof ChampionsRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/mods': typeof ModsRoute
  '/settings': typeof SettingsRoute
  '/workshop': typeof WorkshopRouteWithChildren
  '/workshop/$projectName': typeof WorkshopProjectNameRoute
  '/workshop/': typeof WorkshopIndexRoute
  '/mods_/folder/$folderId': typeof ModsFolderFolderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/champions'
    | '/diagnostics'
    | '/mods'
    | '/settings'
    | '/workshop'
    | '/workshop/$projectName'
    | '/workshop/'
    | '/mods/folder/$folderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/champions'
    | '/diagnostics'
    | '/mods'
    | '/settings'
    | '/workshop/$projectName'
    | '/workshop'
    | '/mods/folder/$folderId'
  id:
    | '__root__'
    | '/'
    | '/champions'
    | '/diagnostics'
    | '/mods'
    | '/settings'
    | '/workshop'
    | '/workshop/$projectName'
    | '/workshop/'
    | '/mods_/folder/$folderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChampionsRoute: typeof ChampionsRoute
  DiagnosticsRoute: typeof DiagnosticsRoute
  ModsRoute: typeof ModsRoute
  SettingsRoute: typeof SettingsRoute
  WorkshopRoute: typeof WorkshopRouteWithChildren
  ModsFolderFolderIdRoute: typeof ModsFolderFolderIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workshop': {
      id: '/workshop'
      path: '/workshop'
      fullPath: '/workshop'
      preLoaderRoute: typeof WorkshopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mods': {
      id: '/mods'
      path: '/mods'
      fullPath: '/mods'
      preLoaderRoute: typeof ModsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostics': {
      id: '/diagnostics'
      path: '/diagnostics'
      fullPath: '/diagnostics'
      preLoaderRoute: typeof DiagnosticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/champions': {
      id: '/champions'
      path: '/champions'
      fullPath: '/champions'
      preLoaderRoute: typeof ChampionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workshop/': {
      id: '/workshop/'
      path: '/'
      fullPath: '/workshop/'
      preLoaderRoute: typeof WorkshopIndexRouteImport
      parentRoute: typeof WorkshopRoute
    }
    '/workshop/$projectName': {
      id: '/workshop/$projectName'
      path: '/$projectName'
      fullPath: '/workshop/$projectName'
      preLoaderRoute: typeof WorkshopProjectNameRouteImport
      parentRoute: typeof WorkshopRoute
    }
    '/mods_/folder/$folderId': {
      id: '/mods_/folder/$folderId'
      path: '/mods/folder/$folderId'
      fullPath: '/mods/folder/$folderId'
      preLoaderRoute: typeof ModsFolderFolderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface WorkshopRouteChildren {
  WorkshopProjectNameRoute: typeof WorkshopProjectNameRoute
  WorkshopIndexRoute: typeof WorkshopIndexRoute
}

const WorkshopRouteChildren: WorkshopRouteChildren = {
  WorkshopProjectNameRoute: WorkshopProjectNameRoute,
  WorkshopIndexRoute: WorkshopIndexRoute,
}

const WorkshopRouteWithChildren = WorkshopRoute._addFileChildren(
  WorkshopRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChampionsRoute: ChampionsRoute,
  DiagnosticsRoute: DiagnosticsRoute,
  ModsRoute: ModsRoute,
  SettingsRoute: SettingsRoute,
  WorkshopRoute: WorkshopRouteWithChildren,
  ModsFolderFolderIdRoute: ModsFolderFolderIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
